Repository TeamNado-Sunbae/NadoSunbae-Android, pull requests merged in 2022-09, with the labels that each got.

#563 [UI] 마이페이지 내 정보 수정 뷰
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ClassRoomReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/custom/CustomSwitchTab.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/QuitActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/SearchIdActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ServiceInqueryActivity.kt
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/layout/activity_quit.xml
  app/src/main/res/layout/activity_search_id.xml
  app/src/main/res/layout/activity_service_inquery.xml
  app/src/main/res/values/strings.xml
Labels: UI, 혜빈선배

#568 Feat : 커뮤니티 메인 게시글 부분
  app/src/main/java/com/nadosunbae_android/app/di/DataSourceModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/NadoSunBaeApplication.kt
  app/src/main/java/com/nadosunbae_android/app/di/NetworkModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/RepositoryModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityMainContentAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/res/layout/fragment_community_main_content.xml
  app/src/main/res/layout/item_community_main.xml
  data/src/main/java/com/nadosunbae_android/data/api/community/CommunityService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/community/CommunityDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/community/CommunityDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/Response.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/community/ResponseCommunityMainData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/community/CommunityRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/community/CommunityMainData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/community/CommunityRepository.kt
Labels: FEAT, 호택선배

#569 Feat/community/base
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/DataSourceModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/NadoSunBaeApplication.kt
  app/src/main/java/com/nadosunbae_android/app/di/NetworkModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/RepositoryModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunitySearchActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityMainContentAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/res/drawable/ic_no_search.xml
  app/src/main/res/drawable/ic_radio_btn_gray.xml
  app/src/main/res/drawable/ic_radio_btn_mint.xml
  app/src/main/res/drawable/ic_search_gray.xml
  app/src/main/res/drawable/rectangle_gray0_height_8.xml
  app/src/main/res/drawable/selector_gray_3_to_main_black_checked.xml
  app/src/main/res/drawable/selector_radio_btn.xml
  app/src/main/res/layout/activity_community_search.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_community_main_content.xml
  app/src/main/res/layout/item_community_main.xml
  app/src/main/res/layout/layout_category_check_box.xml
  app/src/main/res/layout/layout_major_bottomsheet.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/community/CommunityService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/community/CommunityDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/community/CommunityDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/Response.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/community/ResponseCommunityMainData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/community/CommunityRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/community/CommunityMainData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/community/CommunityRepository.kt
Labels: FEAT, 호택선배

#572 Feat/community/post detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/DataSourceModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/NetworkModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/RepositoryModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityMainContentAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityPostDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeQuestionInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReplyInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/item_community_detail.xml
  app/src/main/res/layout/item_community_main.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/community/CommunityService.kt
  data/src/main/java/com/nadosunbae_android/data/api/post/PostService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/community/CommunityDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/community/CommunityDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/post/ResponsePostData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/post/ResponsePostDetailData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/community/CommunityRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/post/PostRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/post/PostData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/post/PostDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/community/CommunityRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/post/PostRepository.kt
Labels: FEAT, 호택선배

#580 Feat/bottomsheet/remote local
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/di/ApiModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/RepositoryModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  buildSrc/src/main/java/Dependencies.kt
  data/build.gradle.kts
  data/src/main/java/com/nadosunbae_android/data/api/main/MainService.kt
  data/src/main/java/com/nadosunbae_android/data/api/major/MajorService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/database/NadoSunbaeDatabase.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/database/NadoSunbaeDatabaseImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/database/dao/MajorListDao.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/database/dao/impl/MajorListDaoImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/database/entity/MajorList.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/home/HomeDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/like/LikeDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/main/MainDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/main/MainDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/major/MajorDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/major/MajorDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/notification/NotificationDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/main/MainMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/major/ResponseMajorListData.kt
  data/src/main/java/com/nadosunbae_android/data/module/DataSourceModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/DatabaseModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/NetworkModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/RepositoryModule.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/classroom/ClassRoomRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/home/HomeRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/like/LikeRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/main/MainRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/major/MajorRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/notification/NotificationRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/post/PostRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/review/ReviewRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/nadosunbae_android/domain/model/major/MajorListData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/main/MainRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/major/MajorRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/main/GetMajorListDataUseCase.kt
Labels: FEAT, 호택선배

#582 Feat/community/write
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/custom/CustomSwitchTab.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_class_room_main_content.xml
  app/src/main/res/layout/fragment_community_main_content.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/item_bottomshhet_community_list.xml
  app/src/main/res/layout/layout_category_check_box.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/post/PostService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/classroom/RequestClassRoomData.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/post/RequestPostWriteData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/post/ResponsePostWriteData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/post/PostRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/SelectableData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/major/MajorListData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/post/PostWriteData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/post/PostRepository.kt
Labels: FEAT, 호택선배

#583 Feat/mypage/network
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage_post_by_me.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/api/user/UserService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/user/UserDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/user/UserDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/user/UserMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/mypage/RequestMyPageModify.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMyPageModify.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMypageMyInfo.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/user/ResponseUserInfo.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/user/ResponseUserPost.kt
  data/src/main/java/com/nadosunbae_android/data/module/DataSourceModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/NetworkModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/RepositoryModule.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/user/UserRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageModifyData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageModifyItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPagePostData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/user/UserInfoData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/user/UserPostData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/user/UserRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageLikeQuestionUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageLikeReviewUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageMyInfoUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPagePostUseCase.kt
Labels: MODIFY, 혜빈선배

#587 Feat : 커뮤니티 메인 필터 및 카테고리에 따른 데이터 변경
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageLikeListActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageReplyActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/layout/activity_my_page_like_list.xml
  app/src/main/res/layout/activity_my_page_post.xml
  app/src/main/res/layout/activity_my_page_reply.xml
  data/src/main/java/com/nadosunbae_android/data/api/major/MajorService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/major/MajorDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/major/MajorDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/module/DataSourceModule.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/major/MajorRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/post/PostRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/SelectableData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/major/MajorRepository.kt
Labels: FEAT, 호택선배

#589 Feat/community/main refresh
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/res/layout/fragment_community_main_content.xml
  app/src/main/res/layout/item_community_main.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#593 Feat/community/write detail
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
Labels: FEAT, 호택선배

#595 [MODIFY] do not run GA in debug mode
  app/src/main/java/com/nadosunbae_android/app/util/FirebaseAnalyticsUtil.kt
Labels: MODIFY, 형기선배

#596 Feat : 커뮤니티 상세 좋아요
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityPostDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityDetailViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/api/like/LikeService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/like/LikeDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/like/LikeDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/like/LikeMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/like/RequestPostLike.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/like/ResponsePostLike.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/like/LikeRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/like/LikeData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/like/LikeItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/like/LikeRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/like/PostLikeDataUseCase.kt
Labels: FEAT, 호택선배

#597 Feat/home/banner
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/adpter/BannerAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/adpter/BannerListAdapter.kt
  app/src/main/res/layout/item_home_banner.xml
  data/src/main/java/com/nadosunbae_android/data/api/app/AppService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/app/AppDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/app/AppDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/app/AppMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/app/ResponseAppBanner.kt
  data/src/main/java/com/nadosunbae_android/data/module/DataSourceModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/NetworkModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/RepositoryModule.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/app/AppRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/app/AppBannerData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/home/Banner.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/app/AppRepository.kt
Labels: FEAT, 혜빈선배

#599 Modify : review network
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/FilterBottomSheetFragment.kt
  data/src/main/java/com/nadosunbae_android/data/api/main/MainService.kt
  data/src/main/java/com/nadosunbae_android/data/api/review/ReviewService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/review/ReviewMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/review/RequestReviewListData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseReviewDetailData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseReviewListData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/review/ReviewRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/review/ReviewFilterItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/review/ReviewPreviewData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/review/ReviewRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/review/GetBackgroundImageListDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/review/GetReviewListDataUseCase.kt
Labels: MODIFY, 형기선배

#601 Modify/sign/UI
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/SpinnerAdapter.kt
  app/src/main/res/drawable-xxhdpi/selector_ic_check_spinner.xml
  app/src/main/res/layout/activity_sign_up_major_info.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: MODIFY, 혜빈선배

#603 Feat : 커뮤니티 상세 원글 삭제 및 댓글 삭제
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityMainContentAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/ContextExt.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDropDownAdapter.kt
  app/src/main/res/layout/activity_community_detail.xml
  data/src/main/java/com/nadosunbae_android/data/api/comment/CommentService.kt
  data/src/main/java/com/nadosunbae_android/data/api/post/PostService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/comment/CommentDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/comment/CommentDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/comment/RequestCommentData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/comment/ResponseCommentData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/comment/ResponseDeleteCommentData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/post/ResponsePostDeleteData.kt
  data/src/main/java/com/nadosunbae_android/data/module/DataSourceModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/NetworkModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/RepositoryModule.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/comment/CommentRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/post/PostRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/comment/CommentData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/comment/DeleteCommentData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/post/PostDeleteData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/comment/CommentRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/post/PostRepository.kt
Labels: FEAT, 호택선배

#605 Modify/banner/reflect api
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/adpter/BannerAdapter.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/app/AppMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/app/ResponseAppBanner.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/app/AppRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/app/AppBannerData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/app/AppRepository.kt
Labels: MODIFY, 혜빈선배

#609 Feat : 앱 버전별 업데이트 관리
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/SplashViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/app/AppService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/app/AppDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/app/AppDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/app/ResponseAppVersion.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/app/AppRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/app/AppVersionData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/app/AppRepository.kt
Labels: FEAT, 호택선배

#613 Feat : 커뮤니티 원글 댓글 신고
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityDetailViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/api/report/ReportService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/report/ReportDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/report/ReportDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/report/RequestReportParam.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/report/ResponseReportData.kt
  data/src/main/java/com/nadosunbae_android/data/module/DataSourceModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/NetworkModule.kt
  data/src/main/java/com/nadosunbae_android/data/module/RepositoryModule.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/report/ReportRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/report/ReportData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/report/ReportRepository.kt
Labels: FEAT, 호택선배

#615 feat : 부적절 사용자 알럿 띄우기
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityMainContentAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_community_write_update.xml
  app/src/main/res/layout/layout_category_check_box.xml
  app/src/main/res/layout/layout_category_update_check_box.xml
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
Labels: FEAT, 호택선배

#619 Feat/mypage/modify profile img
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyImgBottomSheetFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/drawable-hdpi/group_878.png
  app/src/main/res/drawable-mdpi/group_878.png
  app/src/main/res/drawable-xhdpi/group_878.png
  app/src/main/res/drawable-xxhdpi/group_878.png
  app/src/main/res/drawable-xxxhdpi/group_878.png
  app/src/main/res/layout/fragment_modify_img_bottom_sheet.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/module/NetworkModule.kt
Labels: FEAT, 혜빈선배

#622 Modify/600 classroom api
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomSeniorOffAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomSeniorOnAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/viewmodel/ClassRoomQuestionViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/ClassRoomMainContentViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/AuthInterceptor.kt
  app/src/main/res/layout/fragment_class_room_question.xml
  app/src/main/res/layout/item_question_senior_off_question.xml
  app/src/main/res/layout/item_question_senior_on_question.xml
  data/src/main/java/com/nadosunbae_android/data/api/user/UserService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/user/UserDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/user/UserDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/user/UserMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseClassRoomSeniorData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/user/ResponseSeniorList.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/user/UserRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/ClassRoomSeniorData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/user/SeniorListData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/user/UserRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/GetSeniorDataUseCase.kt
Labels: MODIFY, 형기선배

#625 UI : 커뮤니티 전체적인 뷰 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteUpdateActivity.kt
  app/src/main/res/drawable/ic_radio_btn_gray_select.xml
  app/src/main/res/drawable/selector_radio_btn_gray.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_search.xml
  app/src/main/res/layout/layout_category_update_check_box.xml
Labels: UI, 호택선배

#626 [FIX] 전반적인 로직 수정
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeRankingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/adpter/QuestionAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/adpter/QuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/adpter/RankingDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageLikeListActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageReplyActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeQuestionAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_my_page_like_list.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage_like_question.xml
  app/src/main/res/layout/item_mypage_post_by_me.xml
  app/src/main/res/navigation/nav_graph_home.xml
  app/src/main/res/navigation/nav_graph_sign_up.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/user/UserMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/user/ResponseUserPost.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/user/UserPostData.kt
Labels: FIX, MODIFY, 혜빈선배

#627 Feat/notification/server
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/viewmodel/NotificationViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_notification.xml
  data/src/main/java/com/nadosunbae_android/data/api/notification/NotificationService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/notification/NotificationDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/notification/NotificationDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/notification/NotificationMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationDeleteData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationListData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationReadData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/notification/NotificationRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/notification/NotificationData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/notification/NotificationDeleteData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/notification/NotificationListData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/notification/NotificationReadData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/notification/NotificationRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/notification/DeleteNotificationUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/notification/GetNotificationListDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/notification/ReadNotificationUseCase.kt
Labels: FEAT, 호택선배
