Repository TeamNado-Sunbae/NadoSunbae-Android, pull requests merged in 2022-01, with the labels that each got.

#3 #1 [FEAT] bottom_nav_end
  .idea/misc.xml
  app/src/main/java/com/nadosunbae_andorid/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_andorid/data/api/classroom/ClassRoomService.kt
  app/src/main/java/com/nadosunbae_andorid/data/datasource/remote/classroom/ClassRoomDataSource.kt
  app/src/main/java/com/nadosunbae_andorid/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_andorid/data/model/request/classroom/RequestClassRoomData.kt
  app/src/main/java/com/nadosunbae_andorid/data/model/response/classroom/ResponseClassRoomData.kt
  app/src/main/java/com/nadosunbae_andorid/data/repository/classroom/ClassRoomRepository.kt
  app/src/main/java/com/nadosunbae_andorid/data/repository/classroom/ClassRoomRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/MainActivity.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/viewmodel/classRoomViewModel.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/notification/NotificationActivity.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/notification/NotificationFragment.kt
  app/src/main/res/color/selector_nav_menu_icon.xml
  app/src/main/res/color/selector_nav_menu_text.xml
  app/src/main/res/drawable/selector_ic_mypage.xml
  app/src/main/res/drawable/selector_ic_notice.xml
  app/src/main/res/drawable/selector_ic_review.xml
  app/src/main/res/drawable/selector_ic_room.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: FEAT, 호택선배

#14 #2 [FEAT] review_post_view
  .idea/misc.xml
  app/src/main/java/com/nadosunbae_andorid/data/model/review/PreviewData.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/ReviewAdapter.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/StickyHeaderScrollView.kt
  app/src/main/res/drawable/oval_fill_black.xml
  app/src/main/res/drawable/rectangle_border_gray_10dp.xml
  app/src/main/res/drawable/rectangle_border_gray_8dp.xml
  app/src/main/res/drawable/rectangle_fill_blue_8dp.xml
  app/src/main/res/drawable/rectangle_fill_green_8dp.xml
  app/src/main/res/drawable/rectangle_fill_pink_8dp.xml
  app/src/main/res/drawable/rectangle_fill_purple_8dp.xml
  app/src/main/res/drawable/rectangle_fill_yellow_8dp.xml
  app/src/main/res/drawable/shadow_sticky_header.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/source-roots/buildSrc/source-roots.txt
  buildSrc/build/tmp/jar/MANIFEST.MF
Labels: FEAT, 형기선배

#23 #19 [FEAT] review_data_end
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_andorid/data/model/review/PreviewData.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/adapter/ReviewListAdapter.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/viewmodel/ReviewListViewModel.kt
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_list_review.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEAT, 형기선배

#24 Feat/20 classroom senior question
  .idea/misc.xml
  app/src/main/java/com/nadosunbae_andorid/data/model/response/classroom/ResponseClassRoomSeniorData.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/adapter/ClassRoomSeniorOffAdapter.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/adapter/ClassRoomSeniorOnAdapter.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/res/layout/fragment_question.xml
  app/src/main/res/layout/fragment_senior.xml
  app/src/main/res/layout/item_question_senior_off_question.xml
  app/src/main/res/layout/item_question_senior_on_question.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: FEAT, 호택선배

#34 Feat/25 question write all
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/res/color/selector_gray_0_to_main_black.xml
  app/src/main/res/drawable-hdpi/btn_x_black.png
  app/src/main/res/drawable-hdpi/btn_x_gray.png
  app/src/main/res/drawable-mdpi/btn_x_black.png
  app/src/main/res/drawable-mdpi/btn_x_gray.png
  app/src/main/res/drawable-xhdpi/btn_x_black.png
  app/src/main/res/drawable-xhdpi/btn_x_gray.png
  app/src/main/res/drawable-xxhdpi/btn_x_black.png
  app/src/main/res/drawable-xxhdpi/btn_x_gray.png
  app/src/main/res/drawable-xxxhdpi/btn_x_black.png
  app/src/main/res/drawable-xxxhdpi/btn_x_gray.png
  app/src/main/res/drawable/rectangle_no_size_fill_gray_0_8.xml
  app/src/main/res/drawable/rectangle_no_size_fill_main_black_8.xml
  app/src/main/res/drawable/selector_gray_3_to_main_light_text.xml
  app/src/main/res/drawable/selector_rectangle_gray_to_black_14.xml
  app/src/main/res/drawable/selector_rectangle_gray_to_main_black_8.xml
  app/src/main/res/layout/activity_question_write.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up_agreement.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
Labels: FEAT, 호택선배

#37 #35 [MODIFY] review_detail_end
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_andorid/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_andorid/util/BIndingAdapter.kt
  app/src/main/res/layout/activity_review_detail.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/values/strings.xml
Labels: MODIFY, 형기선배

#44 Feat/38 mypage post by me
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_andorid/data/repository/mypage/MyPageRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/res/layout/activity_my_page_post.xml
  app/src/main/res/layout/fragment_my_page_question.xml
  buildSrc/build/libs/buildSrc.jar
Labels: FEAT, 혜빈선배

#48 #12 [FEAT] bottom_sheet_major_end
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/data/model/sign/BottomSheetData.kt
  app/src/main/java/com/nadosunbae_android/data/model/sign/SelectorBottomSheetData.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewTagBoxAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/CustomBottomSheetDialog.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/adapter/SignSelectionAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDecoration.kt
  app/src/main/java/com/nadosunbae_android/util/PixelRatio.kt
  app/src/main/java/com/nadosunbae_android/util/TextUtil.kt
  app/src/main/res/drawable-hdpi/btn_star_empty.png
  app/src/main/res/drawable-hdpi/ic_diamond_empty_default.png
  app/src/main/res/drawable-hdpi/ic_diamond_empty_gray.png
  app/src/main/res/drawable-hdpi/ic_diamond_fill_default.png
  app/src/main/res/drawable-mdpi/btn_star_empty.png
  app/src/main/res/drawable-mdpi/ic_diamond_empty_default.png
  app/src/main/res/drawable-mdpi/ic_diamond_empty_gray.png
  app/src/main/res/drawable-mdpi/ic_diamond_fill_default.png
  app/src/main/res/drawable-xhdpi/btn_star_empty.png
  app/src/main/res/drawable-xhdpi/ic_diamond_empty_default.png
  app/src/main/res/drawable-xhdpi/ic_diamond_empty_gray.png
  app/src/main/res/drawable-xhdpi/ic_diamond_fill_default.png
  app/src/main/res/drawable-xxhdpi/btn_star_empty.png
  app/src/main/res/drawable-xxhdpi/ic_diamond_empty_default.png
  app/src/main/res/drawable-xxhdpi/ic_diamond_empty_gray.png
  app/src/main/res/drawable-xxhdpi/ic_diamond_fill_default.png
  app/src/main/res/drawable-xxxhdpi/btn_star_empty.png
  app/src/main/res/drawable-xxxhdpi/ic_diamond_empty_default.png
  app/src/main/res/drawable-xxxhdpi/ic_diamond_empty_gray.png
  app/src/main/res/drawable-xxxhdpi/ic_diamond_fill_default.png
  app/src/main/res/drawable/selector_btn_star.xml
  app/src/main/res/drawable/selector_drawable_diamond.xml
  app/src/main/res/drawable/selector_ic_btn_like.xml
  app/src/main/res/drawable/selector_rectangle_gray_to_black_8.xml
  app/src/main/res/layout/activity_review_detail.xml
  app/src/main/res/layout/activity_review_write.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_bottomsheet_list.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/layout/item_question_all.xml
  app/src/main/res/layout/item_question_detail_writer.xml
  app/src/main/res/layout/item_review_tag_box.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 형기선배

#54 Feat/53 classroom review
  .idea/misc.xml
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/ClassRoomReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/res/drawable-hdpi/btn_star_filled.png
  app/src/main/res/drawable-mdpi/property_1_filled.png
  app/src/main/res/drawable-xhdpi/property_1_filled.png
  app/src/main/res/drawable-xxhdpi/property_1_filled.png
  app/src/main/res/drawable-xxxhdpi/property_1_filled.png
  app/src/main/res/layout/fragment_class_room_review.xml
  app/src/main/res/values/strings.xml
  buildSrc/build/libs/buildSrc.jar
Labels: FEAT, 호택선배

#56 #55 [FEAT] classroom_info_end
  .idea/misc.xml
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/InformationFragment.kt
  app/src/main/res/layout/fragment_information.xml
Labels: FEAT, 호택선배

#58 Feat/57 notification
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_andorid/data/repository/mypage/MyPageRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/adapter/ClassRoomInfoDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/RetrofitCall.kt
  app/src/main/res/drawable-hdpi/btn_diamond_18.png
  app/src/main/res/drawable-hdpi/img_profile_24.png
  app/src/main/res/drawable-hdpi/img_profile_32.png
  app/src/main/res/drawable-hdpi/img_room_main.png
  app/src/main/res/drawable-mdpi/btn_diamond_18.png
  app/src/main/res/drawable-mdpi/img_profile_24.png
  app/src/main/res/drawable-mdpi/img_profile_32.png
  app/src/main/res/drawable-mdpi/img_room_main.png
  app/src/main/res/drawable-xhdpi/btn_diamond_18.png
  app/src/main/res/drawable-xhdpi/img_profile_24.png
  app/src/main/res/drawable-xhdpi/img_profile_32.png
  app/src/main/res/drawable-xhdpi/img_room_main.png
  app/src/main/res/drawable-xxhdpi/btn_diamond_18.png
  app/src/main/res/drawable-xxhdpi/img_profile_24.png
  app/src/main/res/drawable-xxhdpi/img_profile_32.png
  app/src/main/res/drawable-xxhdpi/img_room_main.png
  app/src/main/res/drawable-xxxhdpi/btn_diamond_18.png
  app/src/main/res/drawable-xxxhdpi/img_profile_24.png
  app/src/main/res/drawable-xxxhdpi/img_profile_32.png
  app/src/main/res/drawable-xxxhdpi/img_room_main.png
  app/src/main/res/layout/activity_information_detail.xml
  app/src/main/res/layout/activity_question_detail.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_question.xml
  app/src/main/res/layout/item_information_detail.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#61 #60 [UI] detail_graphic_asset_end
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/CustomBottomSheetDialog.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/res/drawable/selector_btn_star.xml
  app/src/main/res/drawable/selector_rectangle_gray_to_black_14dp.xml
  app/src/main/res/drawable/selector_rectangle_gray_to_black_8.xml
  app/src/main/res/drawable/selector_text_pick_to_change.xml
  app/src/main/res/drawable/selector_x_btn.xml
  app/src/main/res/layout/activity_find_pw.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up_agreement.xml
  app/src/main/res/layout/activity_sign_up_basic_info.xml
  app/src/main/res/layout/activity_sign_up_major_info.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream.len
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
  drawable-hdpi/property_1_filled.png
  drawable-mdpi/property_1_filled.png
  drawable-xhdpi/property_1_filled.png
  drawable-xxhdpi/property_1_filled.png
  drawable-xxxhdpi/property_1_filled.png
  drawable/drawable-hdpi/property_1_filled.png
  drawable/drawable-mdpi/property_1_filled.png
  drawable/drawable-xhdpi/property_1_filled.png
  drawable/drawable-xxhdpi/property_1_filled.png
  drawable/drawable-xxxhdpi/property_1_filled.png
Labels: UI, 형기선배

#68 64/feat class room question main server
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseClassRoomMainData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/classroom/ClassRoomRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/classroom/ClassRoomRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/adapter/ClassRoomInfoDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/adapter/ClassRoomQuestionMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/util/RetrofitCall.kt
  app/src/main/res/layout/item_question_all.xml
Labels: FEAT, 호택선배

#71 #70 [FIX] review_main_view_end
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/FilterBottomSheetFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/StickyHeaderScrollView.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDialog.kt
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/values/strings.xml
Labels: FIX, 형기선배

#75 #49 [FEAT] review main server
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/data/api/review/ReviewService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/request/review/RequestReviewListData.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseReviewListData.kt
  app/src/main/java/com/nadosunbae_android/data/model/ui/PreviewData.kt
  app/src/main/java/com/nadosunbae_android/data/model/ui/ReviewTagBoxData.kt
  app/src/main/java/com/nadosunbae_android/data/model/ui/SelectBackgroundBoxData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/review/ReviewRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/review/ReviewRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/ClassRoomReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/StickyHeaderScrollView.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewListAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewSelectBackgroundAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewTagBoxAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewListViewModel.kt
  app/src/main/java/com/nadosunbae_android/util/BIndingAdapter.kt
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/layout/item_review_tag_box.xml
Labels: FEAT, 형기선배

#80 Feat/73 question write server
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/request/classroom/RequestClassRoomPostData.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseClassRoomMainData.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseClassRoomWriteData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/classroom/ClassRoomRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/classroom/ClassRoomRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/res/layout/activity_question_write.xml
  app/src/main/res/layout/item_question_all.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#90 #89 [FIX] Set secondMajor visibility
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewListAdapter.kt
  app/src/main/res/layout/item_list_review.xml
Labels: FIX, 형기선배

#96 #88 [FEAT] major select server
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/data/api/main/MainService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/main/MainDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/main/MainDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/main/ResponseMajorListData.kt
  app/src/main/java/com/nadosunbae_android/data/model/ui/MajorData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/main/MainRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/main/MainRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/StickyHeaderScrollView.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/CustomBottomSheetDialog.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDialog.kt
  app/src/main/java/com/nadosunbae_android/util/FilterBottomSheetFragment.kt
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/values/strings.xml
  drawable-hdpi/img_review_main.png
  drawable-mdpi/img_review_main.png
  drawable-xhdpi/img_review_main.png
  drawable-xxhdpi/img_review_main.png
  drawable-xxxhdpi/img_review_main.png
Labels: FEAT, 형기선배

#98 #97 [FIX] bug in CustomBottomSheetDialog close
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/CustomBottomSheetDialog.kt
Labels: FIX, 형기선배

#100 #99 [FEAT] major url server
  app/src/main/java/com/nadosunbae_android/data/api/review/ReviewService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseMajorData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/review/ReviewRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/review/ReviewRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewListViewModel.kt
Labels: FEAT, 형기선배

#104 Feat/95 notification server
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/data/api/notification/NotificationService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/notification/NotificationDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/notification/NotificationDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationDeleteData.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationListData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/notification/NotificationRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/MyFirebaseMessagingService.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/viewmodel/NotificationViewModel.kt
  app/src/main/java/com/nadosunbae_android/util/BIndingAdapter.kt
  app/src/main/res/drawable/oval_fill_notification_oval_6_6.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: FEAT, 호택선배

#112 #110 [FEAT] review detail profile on question
  app/src/main/java/com/nadosunbae_android/util/BIndingAdapter.kt
  app/src/main/res/layout/activity_review_detail.xml
Labels: FEAT, 형기선배

#114 #113 [FIX] item_list_review, stick_header
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_list_review.xml
Labels: FIX, 형기선배

#125 #109 [FEAT] review write server
  app/src/main/java/com/nadosunbae_android/data/api/review/ReviewService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/request/review/RequestPostReview.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseBackgroundImageListData.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/review/ResponsePostReview.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/sign/SelectableData.kt
  app/src/main/java/com/nadosunbae_android/data/model/ui/MajorData.kt
  app/src/main/java/com/nadosunbae_android/data/model/ui/SelectBackgroundBoxData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/review/ReviewRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/review/ReviewRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewRequireTextWatcher.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewSelectBackgroundAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/CustomBottomSheetDialog.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDecoration.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDropDown.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDropDownAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/ResourceUtil.kt
  app/src/main/res/layout/item_bottomsheet_list.xml
  app/src/main/res/layout/item_drop_down.xml
  app/src/main/res/layout/item_list_background.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/layout/view_drop_down.xml
Labels: FEAT, 형기선배

#131 #108 [FEAT] senior persnoal page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/SeniorPersonalActivity.kt
  app/src/main/res/layout/activity_senior_personal.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: FEAT, 형기선배

#132 #127 [FEAT] review alert
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseSignIn.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDialog.kt
  app/src/main/res/layout/dialog_generic.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 형기선배

#138 #137 [FEAT] access_token
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/util/NadoSunBaeApplication.kt
  app/src/main/java/com/nadosunbae_android/util/NadoSunBaeSharedPreference.kt
Labels: FEAT, 호택선배

#139 #133 [FEAT] review filter server
  app/src/main/java/com/nadosunbae_android/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/res/layout/fragment_class_room.xml
Labels: FEAT, 형기선배

#144 Fix/142 notification server data
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
Labels: FIX, 호택선배

#147 Fix/146 notification go change
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
Labels: FIX, 호택선배

#148 #143 [FEAT] review write qa
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/res/layout/activity_review_write.xml
  app/src/main/res/layout/view_custom_edit_text.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 형기선배

#151 Feat/150 notification read
  .idea/misc.xml
  app/src/main/java/com/nadosunbae_android/data/api/notification/NotificationService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/notification/NotificationDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/notification/NotificationDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationReadData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/notification/NotificationRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/viewmodel/NotificationViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/util/BIndingAdapter.kt
  app/src/main/res/drawable/people1_72.9.png
  app/src/main/res/drawable/people2_72.9.png
  app/src/main/res/drawable/people3_72.9.png
  app/src/main/res/drawable/people4_72.9.png
  app/src/main/res/drawable/people5_72.9.png
Labels: FEAT, FIX, 호택선배

#156 #140 [FEAT] review list filter server
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewListViewModel.kt
  app/src/main/java/com/nadosunbae_android/util/CustomDropDownAdapter.kt
  app/src/main/java/com/nadosunbae_android/util/FilterBottomSheetFragment.kt
  app/src/main/res/drawable/selector_icon_filter.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 형기선배

#157 Fix/replies from others
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/adapter/ClassRoomQuestionMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/SeniorPersonalActivity.kt
  app/src/main/res/values/strings.xml
Labels: FIX, 호택선배

#164 #163 [FIX] review filter exit
  app/src/main/java/com/nadosunbae_android/util/FilterBottomSheetFragment.kt
Labels: FIX, 형기선배

#166 #165 [FEAT] review like
  app/src/main/java/com/nadosunbae_android/data/api/ApiService.kt
  app/src/main/java/com/nadosunbae_android/data/api/like/LikeService.kt
  app/src/main/java/com/nadosunbae_android/data/api/review/ReviewService.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/like/LikeDataSource.kt
  app/src/main/java/com/nadosunbae_android/data/datasource/remote/like/LikeDataSourceImpl.kt
  app/src/main/java/com/nadosunbae_android/data/model/request/like/RequestPostLike.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/like/ResponsePostLike.kt
  app/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseReviewDetailData.kt
  app/src/main/java/com/nadosunbae_android/data/repository/like/LikeRepository.kt
  app/src/main/java/com/nadosunbae_android/data/repository/like/LikeRepositoryImpl.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
Labels: FEAT, 형기선배
