Repository TeamNado-Sunbae/NadoSunbae-Android, pull requests merged in 2022-11, with the labels that each got.

#727 [fix] 문제 해결 완료
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeViewModel.kt
Labels: FIX, 혜빈선배

#730 Modify/ga change
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpBasicInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpFinishActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/FirebaseAnalyticsUtil.kt
  app/src/main/res/layout/activity_review_write.xml
Labels: MODIFY, 호택선배

#733 fix : 과방 이슈 해결
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
  app/src/main/res/layout/fragment_class_room_question.xml
Labels: FIX, 호택선배

#735 Fix/proguard delete
  app/build.gradle.kts
  app/release/output-metadata.json
  buildSrc/src/main/java/Dependencies.kt
Labels: FIX, 호택선배

#737 이미지 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_on_boarding_first.xml
Labels: UI, 혜빈선배

#740 fix : 회원가입 부분 이슈 해결
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoFragment.kt
Labels: FIX, 호택선배

#741 Fix/738 modify sign bug
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoFragment.kt
Labels: FIX, 혜빈선배

#743 [FIX] #742 마진값수정
  app/src/main/res/layout/activity_modify_my_info.xml
Labels: UI, 혜빈선배

#745 Fix/744 review write
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
Labels: FIX, 형기선배
