Repository TeamNado-Sunbae/NadoSunbae-Android, pull requests merged in 2022-08, with the labels that each got.

#551 Feat/community/write UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/res/drawable/ic_radio_btn_gray.xml
  app/src/main/res/drawable/ic_radio_btn_mint.xml
  app/src/main/res/drawable/rectangle_gray0_height_8.xml
  app/src/main/res/drawable/selector_gray_3_to_main_black_checked.xml
  app/src/main/res/drawable/selector_radio_btn.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/layout_category_check_box.xml
  app/src/main/res/layout/layout_major_bottomsheet.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#552 Feat/home/view more
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFrameFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeRankingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/res/drawable-hdpi/ic_questionmark.png
  app/src/main/res/drawable-mdpi/ic_questionmark.png
  app/src/main/res/drawable-xhdpi/ic_questionmark.png
  app/src/main/res/drawable-xxhdpi/ic_questionmark.png
  app/src/main/res/drawable-xxxhdpi/ic_questionmark.png
  app/src/main/res/drawable/selector_btn_check.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_frame.xml
  app/src/main/res/layout/fragment_home_question.xml
  app/src/main/res/layout/fragment_home_ranking.xml
  app/src/main/res/layout/fragment_home_review.xml
  app/src/main/res/layout/item_home_question_detail.xml
  app/src/main/res/layout/item_home_ranking.xml
  app/src/main/res/layout/item_home_review_detail.xml
  app/src/main/res/navigation/nav_graph_home.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 혜빈선배

#555 Feat/mypage/UI
  .idea/git_toolbox_prj.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageLikeListActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageReplyActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/drawable-hdpi/ic_edit.png
  app/src/main/res/drawable-mdpi/ic_edit.png
  app/src/main/res/drawable-xhdpi/ic_edit.png
  app/src/main/res/drawable-xxhdpi/ic_edit.png
  app/src/main/res/drawable-xxxhdpi/ic_edit.png
  app/src/main/res/layout/activity_my_page_like_list.xml
  app/src/main/res/layout/activity_my_page_post.xml
  app/src/main/res/layout/activity_my_page_reply.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: FEAT, 혜빈선배

#557 Feat/community/search UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunitySearchActivity.kt
  app/src/main/res/drawable/ic_no_search.xml
  app/src/main/res/drawable/ic_search_gray.xml
  app/src/main/res/layout/activity_community_search.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#558 Fix/547 classroom fragment trans
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ClassRoomReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/custom/CustomSwitchTab.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
Labels: FIX

#560 Fix/community/search UI
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunitySearchActivity.kt
Labels: FIX, 호택선배
