Repository TeamNado-Sunbae/NadoSunbae-Android, pull requests merged in 2022-02, with the labels that each got.

#181 #178 [MODIFY] clean architecture di - review
  app/src/main/java/com/nadosunbae_android/di/RepositoryModule.kt
  app/src/main/java/com/nadosunbae_android/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/SeniorPersonalActivity.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewListAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/adapter/ReviewTagBoxAdapter.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewListViewModel.kt
  app/src/main/java/com/nadosunbae_android/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/layout/item_review_tag_box.xml
  data/src/main/java/com/nadosunbae_android/api/main/MainService.kt
  data/src/main/java/com/nadosunbae_android/api/review/ReviewService.kt
  data/src/main/java/com/nadosunbae_android/datasource/remote/main/MainDataSource.kt
  data/src/main/java/com/nadosunbae_android/datasource/remote/main/MainDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/datasource/remote/review/ReviewDataSource.kt
  data/src/main/java/com/nadosunbae_android/datasource/remote/review/ReviewDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/mapper/main/MainMapper.kt
  data/src/main/java/com/nadosunbae_android/mapper/review/ReviewMapper.kt
  data/src/main/java/com/nadosunbae_android/model/request/review/RequestPostReviewData.kt
  data/src/main/java/com/nadosunbae_android/model/request/review/RequestPutReviewData.kt
  data/src/main/java/com/nadosunbae_android/model/response/major/ResponseMajorListData.kt
  data/src/main/java/com/nadosunbae_android/model/response/review/ResponsePostReviewData.kt
  data/src/main/java/com/nadosunbae_android/model/response/review/ResponsePutReviewData.kt
  data/src/main/java/com/nadosunbae_android/model/response/review/ResponseReviewDetailData.kt
  data/src/main/java/com/nadosunbae_android/model/ui/MajorKeyData.kt
  data/src/main/java/com/nadosunbae_android/repositoryimpl/main/MainRepositoryImpl.kt
  data/src/main/java/com/nadosunbae_android/repositoryimpl/review/ReviewRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/model/main/MajorData.kt
  domain/src/main/java/com/nadosunbae_android/model/review/BackgroundImageData.kt
  domain/src/main/java/com/nadosunbae_android/model/review/MajorInfoData.kt
  domain/src/main/java/com/nadosunbae_android/model/review/ReviewDeleteData.kt
  domain/src/main/java/com/nadosunbae_android/model/review/ReviewDetailData.kt
  domain/src/main/java/com/nadosunbae_android/model/review/ReviewEditItem.kt
  domain/src/main/java/com/nadosunbae_android/model/review/ReviewFilterItem.kt
  domain/src/main/java/com/nadosunbae_android/model/review/ReviewPreviewData.kt
  domain/src/main/java/com/nadosunbae_android/model/review/ReviewWriteData.kt
  domain/src/main/java/com/nadosunbae_android/model/review/ReviewWriteItem.kt
  domain/src/main/java/com/nadosunbae_android/repository/main/MainRepository.kt
  domain/src/main/java/com/nadosunbae_android/repository/review/ReviewRepository.kt
  domain/src/main/java/com/nadosunbae_android/usecase/main/GetMajorListDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/usecase/review/DeleteReviewDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/usecase/review/GetBackgroundImageListDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/usecase/review/GetMajorInfoDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/usecase/review/GetReviewDetailDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/usecase/review/GetReviewListDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/usecase/review/PostReviewDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/usecase/review/PutReviewDataUseCase.kt
Labels: MODIFY, 형기선배

#192 #191 [MODIFY] UI model structure
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewGlobals.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/SeniorPersonalActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/adapter/ReviewSelectBackgroundAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewListViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/CheckMailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/FindPwActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInCustomDialog.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpAgreementActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpBasicInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpFinishActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/SpinnerAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDropDown.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDropDownAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomEditText.kt
  app/src/main/java/com/nadosunbae_android/app/util/FilterBottomSheetFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/ResourceUtil.kt
  app/src/main/java/com/nadosunbae_android/app/util/TextUtil.kt
  app/src/main/res/layout/activity_senior_personal.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/item_bottomsheet_list.xml
  data/src/main/java/com/nadosunbae_android/data/mapper/main/MainMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/ui/MyPageData.kt
  data/src/main/java/com/nadosunbae_android/data/model/ui/PreviewData.kt
  data/src/main/java/com/nadosunbae_android/data/model/ui/ReviewTagBoxData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/main/MainRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/MajorKeyData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/MajorSelectData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/SelectableData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/review/SelectBackgroundBoxData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/main/MainRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/main/GetMajorListDataUseCase.kt
Labels: MODIFY, 형기선배

#195 Modify/189 modify sign branch processing
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpAgreementActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpBasicInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/res/layout/activity_sign_up_basic_info.xml
  app/src/main/res/values/strings.xml
Labels: MODIFY, 혜빈선배

#198 #197 [MODIFY]signin_status
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/ResultWrapper.kt
  app/src/main/java/com/nadosunbae_android/app/util/SafeApiCall.kt
  data/src/main/java/com/nadosunbae_android/data/api/like/LikeService.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInItem.kt
Labels: MODIFY

#201 #200 [MODIFY] sort dropdown position
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDropDown.kt
  app/src/main/res/layout/view_drop_down.xml
Labels: MODIFY, 형기선배

#202 #179 [MODIFY] parcelable model
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/review/ReviewDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInItem.kt
Labels: MODIFY, 형기선배

#206 Fix/205 fix error
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/AppInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/drawable/selector_ic_switch.xml
  app/src/main/res/drawable/selector_text_color_gray3_to_light.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMypageMyInfo.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageMyInfo.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageMyInfoUseCase.kt
Labels: FIX, 혜빈선배

#208 Feat/199_question recently like count
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/AskEveryOneViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDropDown.kt
  app/src/main/res/layout/fragment_ask_everyone.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/layout/item_question_all.xml
  app/src/main/res/layout/view_drop_down.xml
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseClassRoomMainData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseClassRoomQuestionDetail.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseInfoDetailData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseSeniorQuestionData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMypageQuestionData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseReviewListData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/ClassRoomData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/InfoDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/QuestionDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuestionData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/review/ReviewPreviewData.kt
Labels: FEAT, 호택선배

#210 #209 [FEAT] sign_up_branch_process
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
Labels: FEAT, 호택선배

#212 Feat/211 info array
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InformationViewModel.kt
  app/src/main/res/layout/fragment_information.xml
Labels: FEAT, 호택선배

#216 Feat/207 signup branch processing
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpBasicInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpFinishActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/res/drawable-hdpi/img_mail_sent.png
  app/src/main/res/drawable-mdpi/img_mail_sent.png
  app/src/main/res/drawable-xhdpi/img_mail_sent.png
  app/src/main/res/drawable-xxhdpi/img_mail_sent.png
  app/src/main/res/drawable-xxxhdpi/img_mail_sent.png
  app/src/main/res/layout/activity_sign_up_basic_info.xml
  app/src/main/res/layout/activity_sign_up_finish.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/EmailDuplicationCheck.kt
Labels: FEAT, 혜빈선배

#220 #219 [MODIFY] mypage personal question
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/item_mypage_personal_question.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMypageQuestionData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuestionData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageQuestionUseCase.kt
Labels: MODIFY, 혜빈선배

#224 Feat/223 info one to one question like
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
  app/src/main/res/layout/activity_information_detail.xml
  app/src/main/res/layout/fragment_ask_everyone.xml
  app/src/main/res/layout/fragment_senior_personal.xml
  data/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMypageQuestionData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuestionData.kt
Labels: FEAT, 호택선배

#233 #232 [FEAT] mypage lookup version info
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/AppInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/AppInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/activity_app_info.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMyPageVersionData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageVersionData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageVersionUseCase.kt
Labels: FEAT, 혜빈선배

#235 #234 [FEAT] log out
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/LogOutActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/activity_log_out.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMyPageLogOut.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageLogOutData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/PostMyPageLogOutUseCase.kt
Labels: FEAT, 혜빈선배

#238 Modify/237 qa fixes
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomSeniorOffAdapter.kt
  app/src/main/res/layout/activity_information_detail.xml
  app/src/main/res/layout/fragment_senior_personal.xml
Labels: MODIFY, 호택선배

#240 UI/239 classroom UI
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/res/drawable-hdpi/classroom_property.png
  app/src/main/res/drawable-hdpi/ic_right_arrow.png
  app/src/main/res/drawable-mdpi/classroom_property.png
  app/src/main/res/drawable-mdpi/ic_right_arrow.png
  app/src/main/res/drawable-xhdpi/classroom_property.png
  app/src/main/res/drawable-xhdpi/ic_right_arrow.png
  app/src/main/res/drawable-xxhdpi/classroom_property.png
  app/src/main/res/drawable-xxhdpi/ic_right_arrow.png
  app/src/main/res/drawable-xxxhdpi/classroom_property.png
  app/src/main/res/drawable-xxxhdpi/ic_right_arrow.png
  app/src/main/res/drawable/rectangle_border_1_gray0_fill_white_16.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_question_write.xml
  app/src/main/res/layout/activity_senior_personal.xml
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_information.xml
  app/src/main/res/layout/fragment_my_page_question.xml
  app/src/main/res/layout/fragment_question.xml
  app/src/main/res/layout/fragment_senior_personal.xml
  app/src/main/res/values/strings.xml
Labels: UI, 호택선배

#244 Feat/243 information alert button
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoMainAdapter.kt
  app/src/main/res/layout/fragment_information.xml
Labels: FEAT, 호택선배

#247 #214 [UI] reflect review changes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/WebViewActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/res/layout/activity_web_view.xml
  app/src/main/res/layout/dialog_generic.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/values/strings.xml
Labels: MODIFY, 형기선배

#250 Feat/245 one to one question user division
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/NadoSunBaeSharedPreference.kt
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#256 Feat/251 question update
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/classroom/RequestCommentUpdateData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseCommentUpdateData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/classroom/ClassRoomRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/CommentUpdateData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/CommentUpdateItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/classroom/ClassRoomRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/PutCommentUpdateUseCase.kt
Labels: FEAT, 호택선배

#258 #246 [MODIFY] reflect qa review
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/SeniorPersonalActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/adapter/ReviewListAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/ChangeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/DateUtil.kt
  app/src/main/java/com/nadosunbae_android/app/util/FilterBottomSheetFragment.kt
  app/src/main/res/drawable/selector_gray_2_to_main_default.xml
  app/src/main/res/layout/activity_review_detail.xml
  app/src/main/res/layout/activity_senior_personal.xml
  data/src/main/java/com/nadosunbae_android/data/mapper/review/ReviewMapper.kt
Labels: MODIFY, 형기선배

#260 #255 [FEAT] mypage lookup block list
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageBlockFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageBlockAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page_block.xml
  app/src/main/res/layout/fragment_my_page_setting.xml
  app/src/main/res/layout/item_mypage_block.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMyPageBlock.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageBlockData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageBlockUseCase.kt
Labels: FEAT, 혜빈선배

#262 Feat/257 all question division
  app/build.gradle.kts
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomAskEveryoneAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
Labels: FEAT, 호택선배

#264 #259 [FEAT] loading
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/base/LoadableViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewListViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/dialog_generic.xml
  app/src/main/res/layout/dialog_progress.xml
Labels: MODIFY, 형기선배

#267 Feat/263 question one to one all questioner update
  app/build.gradle.kts
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/classroom/RequestWriteUpdateData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseWriteUpdateData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/classroom/ClassRoomRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/WriteUpdateData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/WriteUpdateItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/classroom/ClassRoomRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/PutWriteUpdateUseCase.kt
Labels: FEAT, 호택선배

#269 Feat/268 question specific comment delete
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/include_question_detail_comment_delete.xml
  app/src/main/res/layout/include_question_detail_comment_text.xml
  app/src/main/res/layout/include_question_detail_questioner_delete.xml
  app/src/main/res/layout/include_question_detail_questioner_text.xml
  app/src/main/res/layout/item_question_detail_comment.xml
  app/src/main/res/layout/item_question_detail_questioner.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseDeleteComment.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/classroom/ClassRoomRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/DeleteCommentData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/classroom/ClassRoomRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/DeleteCommentDataUseCase.kt
Labels: FEAT, 호택선배

#271 #261 [FEAT] mypage block and clear
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageBlockFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageBlockAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/mypage/RequestMyPageBlockUpdate.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMyPageBlock.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMyPageBlockUpdate.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageBlockData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageBlockUpdateData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageBlockUpdateItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/PostMyPageBlockUpdateUseCase.kt
Labels: FEAT, 혜빈선배

#273 Feat/270 questioin write delete
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/res/layout/dialog_progress.xml
  data/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/classroom/ClassRoomRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/classroom/ClassRoomRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/DeletePostDataUseCase.kt
Labels: FEAT, 호택선배

#277 #276 [FEAT] certification email
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/AppInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageLikeListActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageReplyActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/NotificationSettingActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/CheckPwMailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpBasicInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpFinishActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/res/layout/activity_check_pw_mail.xml
  app/src/main/res/layout/activity_find_pw.xml
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/layout/activity_my_page_like_list.xml
  app/src/main/res/layout/activity_sign_up_finish.xml
  app/src/main/res/layout/item_list_review.xml
  app/src/main/res/layout/item_mypage_like_review.xml
  app/src/main/res/layout/item_mypage_review.xml
  data/src/main/java/com/nadosunbae_android/data/api/sign/SignService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/sign/RequestCertificationEmail.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseCertificationEmail.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/CertificationEmailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/CertificationEmailItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostCertificationEmailUseCase.kt
Labels: FEAT, 혜빈선배

#280 #278 [MODIFY] modify mypage my info
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageBlockFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageBlockAdapter.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseMyPageBlock.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseCertificationEmail.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageBlockData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/CertificationEmailItem.kt
Labels: MODIFY, 혜빈선배

#283 Feat/274 question one to one all report
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/drawable/inset_8.xml
  app/src/main/res/layout/dialog_report.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/review/ReviewMapper.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/classroom/RequestReportData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseReportData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseReviewDetailData.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseCertificationEmail.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/classroom/ClassRoomRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/ReportData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/ReportItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/review/ReviewDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/classroom/ClassRoomRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/PostReportUseCase.kt
Labels: FEAT, 호택선배
