Repository TeamNado-Sunbae/NadoSunbae-Android, pull requests merged in 2022-10, with the labels that each got.

#631 [MODIFY] #630 1:1질문 상세보기 postId 값 String 으로 변경
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoMainAdapter.kt
Labels: MODIFY, 형기선배

#634 [UI] #632 후기 프로필 상단으로 이동
  app/src/main/res/layout/activity_review_detail.xml
Labels: UI, 형기선배

#636 FIX : 커뮤니티 qa - q0, q1 부분
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityPostDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/item_community_main.xml
  data/src/main/java/com/nadosunbae_android/data/datasource/database/NadoSunbaeDatabaseImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/MajorSelectData.kt
Labels: FIX, 호택선배

#638 차단 사용자 조회 변경된 api반영
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/DeleteMyPageQuitUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageBlockUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/GetMyPageVersionUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/PostMyPageBlockUpdateUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/PostMyPageLogOutUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/PostMyPageResetPasswordUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/PutMyPageModifyUseCase.kt
Labels: MODIFY, 혜빈선배

#640 Feat/639 move to senior detail
  app/build.gradle.kts
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeRankingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/adpter/RankingDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/ResourceUtil.kt
  app/src/main/res/navigation/nav_graph_home.xml
  build.gradle.kts
  data/build.gradle.kts
  domain/build.gradle.kts
Labels: FEAT, 혜빈선배

#641 Fix : 커뮤니티 QA
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityPostDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_community_main_content.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/item_community_detail.xml
  app/src/main/res/layout/item_community_main.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/nadosunbae_android/domain/model/main/SelectableData.kt
Labels: FIX, 호택선배

#643 마이페이지 내 프로필 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/res/layout/activity_modify_my_info.xml
Labels: MODIFY, 혜빈선배

#647 Modify: 과방 1:1 상세보기 수정
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/api/comment/CommentService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/comment/CommentDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/comment/CommentDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/comment/RequestPutCommentData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/comment/CommentRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/comment/CommentData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/comment/CommentRepository.kt
Labels: MODIFY, 형기선배

#649 Fix: 후기 조회 태그 파라미터 및 좋아요 수정
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/viewmodel/ReviewDetailViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/api/review/ReviewService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/review/ReviewDataSourceImpl.kt
Labels: FIX, 형기선배

#646 [FEAT] #644 - universityId 고정값 들어간 부분 수정
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/viewmodel/ClassRoomQuestionViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunitySearchActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunitySearchViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  data/src/main/java/com/nadosunbae_android/data/api/post/PostService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/post/PostDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseSignIn.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/post/PostRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/post/PostRepository.kt
Labels: MODIFY, 혜빈선배

#645 Feat : 푸시 알림
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/debug/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/MyFirebaseMessagingService.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/viewmodel/NotificationViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/notification/NotificationData.kt
Labels: FEAT, 호택선배

#652 Fix/651 review modify
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/review/ReviewMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/review/ResponseReviewDetailData.kt
Labels: FIX, 형기선배

#654 [FEAT] #650 - 마이페이지 Empty View 반영
  app/src/main/res/layout/activity_my_page_post.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, MODIFY, 혜빈선배

#658 Fix/657 classroom select major
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
Labels: FIX, 형기선배

#659 Fix/community qa 3
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityPostDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/layout/fragment_community_main_content.xml
  app/src/main/res/layout/item_community_detail.xml
  app/src/main/res/layout/layout_category_check_box.xml
  app/src/main/res/layout/layout_category_update_check_box.xml
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/major/MajorRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/community/CommunityRadioButtonData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/SelectableData.kt
Labels: FIX, 호택선배

#660 Modify/656 sign up
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpBasicInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/AuthInterceptor.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/layout/fragment_sign_up_major_info.xml
  data/src/main/java/com/nadosunbae_android/data/api/sign/SignService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseFirstDepartment.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseUnivEmail.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/SelectableData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SelectableCheck.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignBottomSheetData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignBottomSheetItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/UnivEmailItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/GetFirstDepartmentUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/GetSecondDepartmentUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostCertificationEmailUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostSignEmailUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostSignInUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostSignNicknameUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostSignUpUseCase.kt
Labels: MODIFY, 혜빈선배

#667 fix : 알림 수정
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/viewmodel/NotificationViewModel.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/notification/NotificationData.kt
Labels: FIX, 호택선배

#668 Modify/665 finish sign up
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpAgreementFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpBasicInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/nav_graph_sign_up.xml
Labels: MODIFY, 혜빈선배

#669 fix : 알림 엠티 처리
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/viewmodel/NotificationViewModel.kt
Labels: FIX, 호택선배

#671 modify : 로그인 안쓰는 코드 삭제
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/NadoSunBaeSharedPreference.kt
Labels: MODIFY, 호택선배

#675 Modify/673 modify profile change bottom sheet
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/ResourceUtil.kt
  app/src/main/res/drawable-hdpi/a_72.png
  app/src/main/res/drawable-hdpi/b_72.png
  app/src/main/res/drawable-hdpi/c_72.png
  app/src/main/res/drawable-hdpi/d_72.png
  app/src/main/res/drawable-hdpi/e_72.png
  app/src/main/res/drawable-mdpi/a_72.png
  app/src/main/res/drawable-mdpi/b_72.png
  app/src/main/res/drawable-mdpi/c_72.png
  app/src/main/res/drawable-mdpi/d_72.png
  app/src/main/res/drawable-mdpi/e_72.png
  app/src/main/res/drawable-xhdpi/a_72.png
  app/src/main/res/drawable-xhdpi/b_72.png
  app/src/main/res/drawable-xhdpi/c_72.png
  app/src/main/res/drawable-xhdpi/d_72.png
  app/src/main/res/drawable-xhdpi/e_72.png
  app/src/main/res/drawable-xxhdpi/a_72.png
  app/src/main/res/drawable-xxhdpi/b_72.png
  app/src/main/res/drawable-xxhdpi/c_72.png
  app/src/main/res/drawable-xxhdpi/d_72.png
  app/src/main/res/drawable-xxhdpi/e_72.png
  app/src/main/res/drawable-xxxhdpi/a_72.png
  app/src/main/res/drawable-xxxhdpi/b_72.png
  app/src/main/res/drawable-xxxhdpi/c_72.png
  app/src/main/res/drawable-xxxhdpi/d_72.png
  app/src/main/res/drawable-xxxhdpi/e_72.png
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/layout/fragment_modify_img_bottom_sheet.xml
Labels: MODIFY, 혜빈선배

#677 Fix : 전체, 커뮤니티, 정책 부분 QA 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/java/com/nadosunbae_android/app/util/TextUtil.kt
  app/src/main/res/layout/activity_app_info.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_community_search.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/activity_community_write_update.xml
  app/src/main/res/layout/activity_find_pw.xml
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/layout/activity_my_page_classroom_review.xml
  app/src/main/res/layout/activity_my_page_like_list.xml
  app/src/main/res/layout/activity_my_page_post.xml
  app/src/main/res/layout/activity_my_page_reply.xml
  app/src/main/res/layout/activity_notification_setting.xml
  app/src/main/res/layout/activity_question_detail.xml
  app/src/main/res/layout/activity_question_write.xml
  app/src/main/res/layout/fragment_ask_everyone.xml
  app/src/main/res/layout/fragment_class_room_main_content.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_question.xml
  app/src/main/res/layout/fragment_home_ranking.xml
  app/src/main/res/layout/fragment_home_review.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_block.xml
  app/src/main/res/layout/fragment_my_page_setting.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_senior.xml
  app/src/main/res/layout/fragment_senior_personal.xml
  app/src/main/res/layout/fragment_sign_up_agreement2.xml
  app/src/main/res/layout/fragment_sign_up_basic_info.xml
  app/src/main/res/layout/fragment_sign_up_major_info.xml
Labels: FIX, 호택선배

#681 fix : 홈 -> 커뮤니티 무한 로딩 해결
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
Labels: FIX, 호택선배

#683 Fix/classroom p0 : 바텀시트 부분
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/di/ApiModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/ClassRoomMainContentViewModel.kt
  app/src/main/res/layout/item_notification.xml
Labels: FIX, 호택선배

#686 [MODIFY] 선배 개인페이지수정
  app/src/main/res/layout/fragment_senior_personal.xml
Labels: MODIFY, 혜빈선배

#689 Modify/classroom qa
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_question_write.xml
  data/src/main/java/com/nadosunbae_android/data/api/classroom/ClassRoomService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/classroom/ClassRoomDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/post/RequestPostWriteData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/classroom/ClassRoomRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/QuestionDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/classroom/ClassRoomRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/DeleteCommentDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/GetInformationDetailUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/GetQuestionDetailDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/GetQuestionSeniorListDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/GetSeniorDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/GetSeniorPersonalDataUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/PostClassRoomWriteUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/PostQuestionCommentWriteUseCase.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/classroom/PutCommentUpdateUseCase.kt
Labels: MODIFY, 호택선배

#690 Modify/687 modify qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomSeniorOnAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
  app/src/main/res/drawable-hdpi/ic_cancel.png
  app/src/main/res/drawable-mdpi/ic_cancel.png
  app/src/main/res/drawable-v24/ic_right_arrow_mint.png
  app/src/main/res/drawable-v24/rectangle_border_gray0_22.xml
  app/src/main/res/drawable-xhdpi/ic_cancel.png
  app/src/main/res/drawable-xxhdpi/ic_cancel.png
  app/src/main/res/drawable-xxxhdpi/ic_cancel.png
  app/src/main/res/layout/fragment_class_room_main_content.xml
  app/src/main/res/layout/fragment_class_room_question.xml
  app/src/main/res/layout/fragment_senior_personal.xml
  app/src/main/res/layout/item_question_senior_on_question.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: MODIFY, 혜빈선배

#694 Feat/693 senior question
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/res/drawable/ic_plus_default_color.xml
  app/src/main/res/drawable/rectangle_round_fill_black_40.xml
  app/src/main/res/layout/activity_question_detail.xml
  data/src/main/java/com/nadosunbae_android/data/model/response/post/ResponsePostDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/QuestionDetailData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/post/PostDetailData.kt
Labels: FEAT, 형기선배

#697 Modify/687 modify qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
Labels: MODIFY, 혜빈선배

#700 [MODIFY] #699 과방 선배랭킹 목록 질문불가 선배 포함
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/question/ClassRoomQuestionFragment.kt
Labels: MODIFY, 형기선배

#698 Modify : 큐에이
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityMainContentFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/SplashViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpMajorInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/layout/fragment_community_main_content.xml
  app/src/main/res/layout/item_community_main.xml
Labels: MODIFY, 호택선배

#702 [MODIFY] #701 과방 질문목록 margin QA 반영
  app/src/main/res/layout/fragment_class_room_question.xml
  app/src/main/res/layout/item_question_all.xml
Labels: MODIFY, 형기선배

#706 Modify : 온보딩 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-hdpi/img_onboarding2.png
  app/src/main/res/drawable-hdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-hdpi/img_onboarding_two.png
  app/src/main/res/drawable-mdpi/img_onboarding2.png
  app/src/main/res/drawable-mdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-mdpi/img_onboarding_two.png
  app/src/main/res/drawable-xhdpi/img_onboarding2.png
  app/src/main/res/drawable-xhdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-xhdpi/img_onboarding_two.png
  app/src/main/res/drawable-xxhdpi/img_onboarding2.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_two.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding2.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_two.png
  app/src/main/res/layout/fragment_on_boarding_first.xml
  app/src/main/res/layout/fragment_on_boarding_second.xml
  app/src/main/res/values/strings.xml
Labels: MODIFY, 호택선배

#705 [UI] #704 1:1질문 작성뷰 타이틀 문구 변경
  app/src/main/res/layout/activity_question_write.xml
  app/src/main/res/values/strings.xml
Labels: UI, 형기선배

#708 Modify : 과방 바텀시트 어댑터 수정 및 알림 Response 변경
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomBottomSheetDialog.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/notification/ResponseNotificationData.kt
Labels: MODIFY, 호택선배

#711 Fix/710 reflect qa
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeQuestionAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostInfoAdapter.kt
  app/src/main/res/drawable-hdpi/frame_919.png
  app/src/main/res/drawable-mdpi/frame_919.png
  app/src/main/res/drawable-xhdpi/frame_919.png
  app/src/main/res/drawable-xxhdpi/frame_919.png
  app/src/main/res/drawable-xxxhdpi/frame_919.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_mypage_post_by_me.xml
Labels: FIX, 혜빈선배

#712 Modify : 커뮤니티 부분 QA
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/adapter/CommunityMainContentAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/viewmodel/CommunityWriteUpdateViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/adapter/MajorSelectAdapter.kt
  app/src/main/res/layout/activity_community_detail.xml
Labels: MODIFY, 호택선배

#717 [FIX] #716 userId가 일치하지 않는도록 filter 추가
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
Labels: FIX, 형기선배

#719 Modify/718 review policy qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
Labels: MODIFY, 형기선배

#714 Modify : 알림 QA
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/viewmodel/NotificationViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
Labels: MODIFY, 호택선배

#721 [FIX] #720 후기 수정 글자수 표시
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/review/ReviewWriteActivity.kt
Labels: FIX, 형기선배

#725 Modify : GA 코드 수정사항
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/community/CommunityWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/FirebaseAnalyticsUtil.kt
Labels: MODIFY, 호택선배
