Repository TeamNado-Sunbae/NadoSunbae-Android, pull requests merged in 2022-03, with the labels that each got.

#285 #265 [FEAT] refresh token
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/ApiModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/base/LoadableViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewListViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/AuthInterceptor.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/java/com/nadosunbae_android/app/util/ManageUtil.kt
  app/src/main/java/com/nadosunbae_android/app/util/NadoSunBaeSharedPreference.kt
  app/src/main/res/layout/item_list_review.xml
  data/src/main/java/com/nadosunbae_android/data/api/sign/SignService.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseRenewalToken.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseSignIn.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/RenewalTokenData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostSignInUseCase.kt
Labels: FEAT, 형기선배

#294 APK 자동배포 CD 추가
  .github/workflows/main.yml
Labels: CHORE, 형기선배

#296 #293 [FEAT] mypage quit
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/QuitAlertCustomDialog.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignUpAgreementActivity.kt
  app/src/main/res/layout/activity_quit_alert_custom_dialog.xml
  data/src/main/java/com/nadosunbae_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/mypage/RequestQuit.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseQuitData.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuitData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuitItem.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/mypage/DeleteMyPageQuitUseCase.kt
Labels: FEAT, 혜빈선배

#300 #297 [MODIFY] reflect qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/AppInfoFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseQuitData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuitData.kt
Labels: MODIFY, 혜빈선배

#301 Feat/299 information update delete report
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
Labels: FEAT, 호택선배

#302 #278 [MODIFY] mypage modify profile
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
Labels: MODIFY, 혜빈선배

#305 Feat/304 senior to mypage
  app/build.gradle.kts
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
Labels: FEAT, 호택선배

#306 #303 [MODIFY] modify quit bug
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/mypage/MypageMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/request/mypage/RequestQuit.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/mypage/ResponseQuitData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuitData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/mypage/MyPageQuitItem.kt
Labels: MODIFY, 혜빈선배

#309 #308 [FIX] notification_list
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
Labels: FIX, 호택선배

#312 #266 [FEAT] add ga
  .github/workflows/main.yml
  app/build.gradle.kts
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: FEAT, 형기선배

#313 #287 [FEAT] auto login
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/di/UseCaseModule.kt
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/SplashViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/AuthInterceptor.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/nadosunbae_android/data/api/sign/SignService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseRenewalToken.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/RenewalTokenData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostRenewalTokenUseCase.kt
Labels: FEAT, 형기선배

#316 #315 [FIX] fix token preference
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/AuthInterceptor.kt
Labels: FIX, 형기선배

#317 #307 [FEAT] add onboarding
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/onboarding/OnBoardingFirstFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/onboarding/OnBoardingForthFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/onboarding/OnBoardingSecondFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/onboarding/OnBoardingThirdFragment.kt
  app/src/main/res/drawable-hdpi/ic_logo.png
  app/src/main/res/drawable-hdpi/img_onboarding2.png
  app/src/main/res/drawable-hdpi/img_onboarding3.png
  app/src/main/res/drawable-hdpi/img_onboarding4.png
  app/src/main/res/drawable-hdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-mdpi/ic_logo.png
  app/src/main/res/drawable-mdpi/img_onboarding2.png
  app/src/main/res/drawable-mdpi/img_onboarding3.png
  app/src/main/res/drawable-mdpi/img_onboarding4.png
  app/src/main/res/drawable-mdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-xhdpi/ic_logo.png
  app/src/main/res/drawable-xhdpi/img_onboarding2.png
  app/src/main/res/drawable-xhdpi/img_onboarding3.png
  app/src/main/res/drawable-xhdpi/img_onboarding4.png
  app/src/main/res/drawable-xhdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-xxhdpi/ic_logo.png
  app/src/main/res/drawable-xxhdpi/img_onboarding2.png
  app/src/main/res/drawable-xxhdpi/img_onboarding3.png
  app/src/main/res/drawable-xxhdpi/img_onboarding4.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_shadow.png
  app/src/main/res/drawable-xxxhdpi/ic_logo.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding2.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding3.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding4.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_shadow.png
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_on_boarding_first.xml
  app/src/main/res/layout/fragment_on_boarding_forth.xml
  app/src/main/res/layout/fragment_on_boarding_second.xml
  app/src/main/res/layout/fragment_on_boarding_third.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 혜빈선배

#319 Fix/311 classroom nickname click
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomSeniorOffAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomSeniorOnAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainGlobals.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
Labels: FEAT, 호택선배

#323 #322 [FIX] mpage_to_classroom_back
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
Labels: FIX, 호택선배

#325 #324 [FEAT] senior_personal_class_review
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
Labels: FEAT, 호택선배

#327 #321 [FEAT] alarm setting end
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/NotificationSettingActivity.kt
Labels: FEAT, 혜빈선배

#329 #328 [FEAT] mypage question alarm end
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/activity_modify_my_info.xml
Labels: FEAT, MODIFY, 혜빈선배

#331 Feat/326 senior personal block
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#333 #330 [MODIFY] logout alert end
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/values/strings.xml
Labels: MODIFY, 혜빈선배

#335 Modify/332 date to text
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/item_notification.xml
Labels: MODIFY, 호택선배

#337 UI/336 classroom touch info like
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/res/layout/activity_information_detail.xml
  app/src/main/res/layout/fragment_question.xml
Labels: UI, 호택선배

#338 #334 [MODIFY] manage backstack
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/AppInfoFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageBlockFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
Labels: MODIFY, 혜빈선배

#341 Modify/340 senior personal page
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReviewAdapter.kt
  app/src/main/res/layout/fragment_senior_personal.xml
  data/src/main/java/com/nadosunbae_android/data/mapper/classroom/ClassRoomMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/classroom/ResponseSeniorPersonalData.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/SeniorPersonalData.kt
Labels: MODIFY, 호택선배

#343 #314 [FEAT] report review
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/java/com/nadosunbae_android/app/util/ToastUtil.kt
  app/src/main/res/layout/dialog_report.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 형기선배

#344 #339 [MODIFY] modify loading
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageBlockFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageLikeListActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageReplyActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageSettingFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeQuestionAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReplyAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_find_pw.xml
  app/src/main/res/layout/activity_modify_my_info.xml
  app/src/main/res/layout/activity_my_page_classroom_review.xml
  app/src/main/res/layout/activity_my_page_like_list.xml
  app/src/main/res/layout/activity_my_page_post.xml
  app/src/main/res/layout/activity_my_page_reply.xml
  app/src/main/res/layout/activity_question_detail.xml
  app/src/main/res/layout/activity_review_detail.xml
  app/src/main/res/layout/activity_review_write.xml
  app/src/main/res/layout/fragment_ask_everyone.xml
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_class_room_review.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_information.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_block.xml
  app/src/main/res/layout/fragment_my_page_question.xml
  app/src/main/res/layout/fragment_my_page_setting.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_question.xml
  app/src/main/res/layout/fragment_senior_personal.xml
Labels: UI, MODIFY, 혜빈선배

#346 #320 [MODIFY] review my profile
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
Labels: MODIFY, 형기선배

#352 #350 [FIX] fix error
  app/src/main/res/layout/activity_find_pw.xml
Labels: FIX, 혜빈선배

#355 #354 [FIX] block_cancel_end
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageBlockFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageBlockAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
Labels: FIX, 호택선배

#359 #349 [MODIFY] reflect mypage qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageBlockFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageLikeListActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPagePostActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageReplyActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/onboarding/OnBoardingForthFragment.kt
  app/src/main/res/layout/activity_my_page_classroom_review.xml
  app/src/main/res/layout/activity_my_page_like_list.xml
  app/src/main/res/layout/activity_my_page_post.xml
  app/src/main/res/layout/activity_my_page_reply.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_block.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/NicknameDuplicationCheck.kt
Labels: FIX, UI, MODIFY, 혜빈선배

#361 Feat/358 classroom notification loading
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/AskEveryOneViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/viewmodel/NotificationViewModel.kt
  app/src/main/res/layout/fragment_notification.xml
Labels: FEAT, 호택선배

#364 #347 [MODIFY] review qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/adapter/ReviewSelectBackgroundAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/review/ReviewMapper.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/review/ReviewWriteData.kt
Labels: MODIFY, 형기선배

#363 #360 [FEAT] add onboarding sharedPreferences
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
Labels: FEAT, 혜빈선배

#366 #362 [FEAT] notification_fcm_end
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/MyFirebaseMessagingService.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/res/layout/item_question_detail_comment.xml
  app/src/main/res/layout/item_question_detail_questioner.xml
Labels: FEAT, 호택선배

#372 #370 [FEAT] version_update
  app/build.gradle.kts
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
Labels: FEAT, 호택선배

#378 UI/369 empty view
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_information.xml
  app/src/main/res/layout/fragment_senior_personal.xml
  app/src/main/res/values/strings.xml
Labels: UI, 호택선배

#380 Fix/379 senior back info profile image
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_information.xml
  app/src/main/res/layout/fragment_senior_personal.xml
Labels: FIX, 호택선배

#375 #373 [UI] empty review
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/adapter/ReviewListAdapter.kt
  app/src/main/res/layout/fragment_review.xml
Labels: UI, 형기선배

#383 UI/381 design qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/activity_question_write.xml
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_senior_personal.xml
  app/src/main/res/values/strings.xml
Labels: UI, 호택선배

#385 #384 [MODIFY] classroom_last_item_line_delete
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomAskEveryoneAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionMainAdapter.kt
  app/src/main/res/layout/fragment_ask_everyone.xml
  app/src/main/res/layout/fragment_information.xml
Labels: MODIFY, 호택선배

#387 Modify/386 update write cancel dialog
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/values/strings.xml
Labels: MODIFY, 호택선배

#389 #388 [MODIFY] notification_time_change
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
Labels: MODIFY, 호택선배

#393 UI/390 classroom notification lineheight
  app/src/main/res/layout/activity_information_detail.xml
  app/src/main/res/layout/activity_question_write.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_senior_personal.xml
  app/src/main/res/layout/include_question_detail_comment_text.xml
  app/src/main/res/layout/include_question_detail_questioner_text.xml
  app/src/main/res/layout/item_information_detail.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_question_all.xml
  app/src/main/res/layout/item_question_detail_writer.xml
  app/src/main/res/layout/item_question_senior_off_question.xml
  app/src/main/res/layout/item_question_senior_on_question.xml
Labels: UI, 호택선배

#394 #392 [MODIFY] bug end
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageLikeListActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReviewAdapter.kt
Labels: MODIFY, 혜빈선배

#399 #398 [FEAT] mypage_use
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReplyAdapter.kt
Labels: FEAT, 호택선배

#400 Update MyPageClassroomReviewActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
Labels: FIX, 호택선배

#402 #401 [FIX] mypage_bug
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
Labels: FIX, 호택선배

#405 #382 [MODIFY] ga more
  app/src/main/java/com/nadosunbae_android/app/presentation/base/BaseActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/SplashViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/viewmodel/SignUpBasicInfoViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/FirebaseAnalyticsUtil.kt
  app/src/main/java/com/nadosunbae_android/app/util/NadoSunBaeSharedPreference.kt
  app/src/main/res/layout/item_review_tag_box.xml
  app/src/main/res/values/strings.xml
Labels: MODIFY, 형기선배

#411 #409 [MODIFY] modify sign hint
  app/src/main/res/layout/activity_sign_up_basic_info.xml
  app/src/main/res/values/strings.xml
Labels: MODIFY, 혜빈선배

#412 Feat/403 float dialog bad user
  app/src/main/java/com/nadosunbae_android/app/di/ApiModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/ResultWrapper.kt
  app/src/main/java/com/nadosunbae_android/app/util/SafeApiCall.kt
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/nadosunbae_android/domain/model/network/ErrorBody.kt
Labels: FEAT, 호택선배

#414 #408 [UI] review write characters
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/activity_review_write.xml
Labels: UI, 형기선배

#415 Feat/413 notification detail quit dialog
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/dialog_delete_post.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 호택선배

#418 Fix/416 review bad user
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/InfoDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainGlobals.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  data/src/main/java/com/nadosunbae_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseSignIn.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
Labels: FIX, 호택선배

#420 #410 [FIX] update major
  app/src/main/java/com/nadosunbae_android/app/di/ViewModelModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/ModifyMyInfoActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/FirebaseAnalyticsUtil.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/main/MajorSelectData.kt
Labels: FIX, 형기선배

#421 Fix/419 qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoDetailAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/QuestionWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/viewmodel/SeniorPersonalViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/item_information_detail.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/nadosunbae_android/domain/model/classroom/InfoDetailData.kt
Labels: FIX, 호택선배

#423 #422 [FIX] finish after review write complete
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewWriteActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
Labels: FIX, 형기선배

#426 Fix/425 login
  app/src/main/java/com/nadosunbae_android/app/di/ApiModule.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/SplashViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  data/src/main/java/com/nadosunbae_android/data/api/sign/SignService.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSource.kt
  data/src/main/java/com/nadosunbae_android/data/datasource/remote/sign/SignDataSourceImpl.kt
  data/src/main/java/com/nadosunbae_android/data/model/response/sign/ResponseSignIn.kt
  data/src/main/java/com/nadosunbae_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
  domain/src/main/java/com/nadosunbae_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/nadosunbae_android/domain/usecase/sign/PostRenewalTokenUseCase.kt
Labels: FIX, 호택선배

#429 [MODIFY] modify text
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/InformationDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
Labels: MODIFY, 혜빈선배

#430 #427 [MODIFY] track active user
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/FirebaseAnalyticsUtil.kt
  app/src/main/java/com/nadosunbae_android/app/util/NadoSunBaeSharedPreference.kt
Labels: MODIFY, 형기선배

#434 #433 [FIX] info_writer_tag_end
  app/src/main/java/com/nadosunbae_android/app/util/BIndingAdapter.kt
  app/src/main/res/layout/item_information_detail.xml
Labels: FIX, 호택선배

#436 #432 [FIX] review permission check
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
Labels: FIX, 형기선배

#440 Fix/437 report review no write alert dialog
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/AskEveryoneFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomAskEveryoneAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomQuestionMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainGlobals.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeQuestionInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReplyAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReplyInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
Labels: FIX, 호택선배

#442 Fix/441 report bad user division
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/SeniorPersonalFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/adapter/ClassRoomInfoMainAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeQuestionAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeQuestionInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageLikeReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPagePostInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReplyAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReplyInfoAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
Labels: FIX, 호택선배

#444 #443 [FIX] report_division_qa_end
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/adapter/MyPageReviewAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewWriteViewModel.kt
Labels: FIX, 호택선배

#446 #445 [UI] modify graphic icons
  app/src/main/res/drawable-hdpi/ic_graphic_bomb.png
  app/src/main/res/drawable-hdpi/ic_graphic_compass.png
  app/src/main/res/drawable-hdpi/ic_graphic_cube.png
  app/src/main/res/drawable-hdpi/ic_graphic_diamond.png
  app/src/main/res/drawable-hdpi/ic_graphic_honey.png
  app/src/main/res/drawable-hdpi/ic_graphic_pencil.png
  app/src/main/res/drawable-mdpi/ic_graphic_bomb.png
  app/src/main/res/drawable-mdpi/ic_graphic_compass.png
  app/src/main/res/drawable-mdpi/ic_graphic_cube.png
  app/src/main/res/drawable-mdpi/ic_graphic_diamond.png
  app/src/main/res/drawable-mdpi/ic_graphic_honey.png
  app/src/main/res/drawable-mdpi/ic_graphic_pencil.png
  app/src/main/res/drawable-xhdpi/ic_graphic_bomb.png
  app/src/main/res/drawable-xhdpi/ic_graphic_compass.png
  app/src/main/res/drawable-xhdpi/ic_graphic_cube.png
  app/src/main/res/drawable-xhdpi/ic_graphic_diamond.png
  app/src/main/res/drawable-xhdpi/ic_graphic_honey.png
  app/src/main/res/drawable-xhdpi/ic_graphic_pencil.png
  app/src/main/res/drawable-xxhdpi/ic_graphic_bomb.png
  app/src/main/res/drawable-xxhdpi/ic_graphic_compass.png
  app/src/main/res/drawable-xxhdpi/ic_graphic_cube.png
  app/src/main/res/drawable-xxhdpi/ic_graphic_diamond.png
  app/src/main/res/drawable-xxhdpi/ic_graphic_honey.png
  app/src/main/res/drawable-xxhdpi/ic_graphic_pencil.png
  app/src/main/res/drawable-xxxhdpi/ic_graphic_bomb.png
  app/src/main/res/drawable-xxxhdpi/ic_graphic_compass.png
  app/src/main/res/drawable-xxxhdpi/ic_graphic_cube.png
  app/src/main/res/drawable-xxxhdpi/ic_graphic_diamond.png
  app/src/main/res/drawable-xxxhdpi/ic_graphic_honey.png
  app/src/main/res/drawable-xxxhdpi/ic_graphic_pencil.png
Labels: UI, 형기선배

#449 #448 [MODIFY] ga property
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/nadosunbae_android/app/util/FirebaseAnalyticsUtil.kt
  app/src/main/res/values/strings.xml
Labels: MODIFY, 형기선배

#452 #451 [FIX] fix bug
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/mypage/MyPageClassroomReviewActivity.kt
Labels: FIX, 혜빈선배

#454 Fix/453 review permission
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewGlobals.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/viewmodel/ReviewDetailViewModel.kt
Labels: FIX, 형기선배

#457 #456 [FIX] sync MainGlobals and ReviewGlobals
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/review/ReviewGlobals.kt
  domain/src/main/java/com/nadosunbae_android/domain/model/sign/SignInData.kt
Labels: FIX, 형기선배

#458 Fix/450 last qa
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/ClassRoomFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/classroom/QuestionDetailActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/NotificationFragment.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/notification/adapter/NotificationAdapter.kt
  app/src/main/java/com/nadosunbae_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/nadosunbae_android/app/util/CustomDialog.kt
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/values/strings.xml
Labels: FIX, 호택선배

#459 #455 [UI] reflect qa
  app/src/main/res/layout/activity_information_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/include_question_detail_comment_text.xml
  app/src/main/res/layout/item_mypage_like_question.xml
Labels: UI, 혜빈선배

#461 #460 [UI] classroom_info_margin
  app/src/main/res/layout/fragment_class_room.xml
  app/src/main/res/layout/fragment_information.xml
  app/src/main/res/layout/fragment_question.xml
Labels: UI, 호택선배

#463 #462 [UI] reflect ui
  app/src/main/res/layout/activity_onboarding.xml
Labels: UI, 혜빈선배
